version: "3.7"

services:
  react:
    image: node:${NODE_TAG}
    container_name: ${PROJECT_NAME}_react
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "${REACT_PORT}:3000"
    expose:
      - "3000"
    command: sh -c "npm install && npm start"

  # traefik:
  #   image: traefik:v2.0
  #   container_name: "${PROJECT_NAME}_traefik"
  #   command: --api.insecure=true --providers.docker
  #   volumes:
  #   - /var/run/docker.sock:/var/run/docker.sock