version: "3.7"

services:
# Enable a NodeJS container for React development
# Copy this file and name it docker-compose.override.yml
# The new file will be ignored by git so the overrides will be local only
  react:
    image: wodby/node:$NODE_TAG
    container_name: "${PROJECT_NAME}_react"
    working_dir: /var/www/html/
    labels:
    - "traefik.http.services.${PROJECT_NAME}_react.loadbalancer.server.port=3000"
    - "traefik.http.routers.${PROJECT_NAME}_react.rule=Host(`react.${PROJECT_BASE_URL}`)"
    expose:
    - "3000"
    volumes:
    - ./:/var/www/html
    command: sh -c 'npm install && tail -f /dev/null'
